SELECT NOW();
-- INSERT INTO roles(id, title, code, created_on, updated_on)
--  VALUES
--  (1, 'Administrator', 'Administrator', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--  (2, 'Regular', 'Regular', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ;

--  INSERT INTO category(id, category_name, abbreviation, added_on, updated_on)
--  VALUES
--   (1,"Food and Edibles", "FE", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (2,"Clothing and apparels", "CA", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (3, "Footwear and Shoes", "FS", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (4, "Electronics and Gadgets", "EG", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (5, "Games and Toys", "GT", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (6, "Sports Products", "SP", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (7, "Furniture", "F", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (8, "Medical Supplies", "MS", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--   (9, "Toys", "T", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
--   INSERT INTO country (id,title,abbreviation, added_on, updated_on)
--   VALUES
--   (1, 'Nigeria', 'NGR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
